import '../Home_screen/popular_items_grid.dart';

//List of items
List<FoodItems> sweetsList = [
  FoodItems(
    name: "Gulab Jamun",
    price: 6.67,
    rating: 4.5,
    noOfPeople: 100,
    img: "assets/gulabjamun.png",
    description: "Sweet dish from India made from khoya and sugar syrup.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Boondi Ladoo",
    price: 5.33,
    rating: 4.3,
    noOfPeople: 80,
    img: "assets/boondiladdoo.png",
    description: "A popular Indian sweet made from gram flour and sugar.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Dhodha",
    price: 8.00,
    rating: 4.0,
    noOfPeople: 50,
    img: "assets/dhodha.png",
    description: "A traditional sweet made from milk and sugar.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Ghewar",
    price: 6.00,
    rating: 4.6,
    noOfPeople: 70,
    img: "assets/ghewar.png",
    description: "A Rajasthani sweet made of flour soaked in sugar syrup.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Kaju Katli",
    price: 13.33,
    rating: 4.8,
    noOfPeople: 40,
    img: "assets/kajukatli.png",
    description: "A diamond-shaped sweet made from cashew nuts.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Rasgulla",
    price: 5.00,
    rating: 4.7,
    noOfPeople: 90,
    img: "assets/rasgulla.png",
    description: "A spongy and syrupy sweet made from cottage cheese.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Rasmalai",
    price: 7.33,
    rating: 4.9,
    noOfPeople: 60,
    img: "assets/rasmalai.png",
    description: "Soft cheese balls soaked in creamy milk.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Jalebi",
    price: 4.67,
    rating: 4.5,
    noOfPeople: 120,
    img: "assets/jalebi.png",
    description: "Crispy fried spirals soaked in saffron-flavored sugar syrup.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Pedha",
    price: 6.00,
    rating: 4.6,
    noOfPeople: 65,
    img: "assets/pedha.png",
    description: "A soft milk-based sweet flavored with cardamom.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Milkcake",
    price: 8.67,
    rating: 4.7,
    noOfPeople: 50,
    img: "assets/milkcake.png",
    description: "A dense, caramelized sweet made from thickened milk.",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Sandesh",
    price: 5.67,
    rating: 4.4,
    noOfPeople: 75,
    img: "assets/sandesh.png",
    description: "A light and fresh Bengali sweet made from chhena (cheese).",
    category: "Sweets",
    continent: "Indian",
  ),
  FoodItems(
    name: "Kulfi",
    price: 7.00,
    rating: 4.8,
    noOfPeople: 85,
    img: "assets/kulfi.png",
    description: "Traditional Indian ice cream flavored with saffron and pistachios.",
    category: "Sweets",
    continent: "Indian",
  ),
];
List<FoodItems> momosList = [
  FoodItems(
    name: "Chilli Momos",
    price: 8.00,
    rating: 4.2,
    noOfPeople: 150,
    img: "assets/chillimomos.png",
    description: "Spicy momos served with a rich chilli sauce.",
    category: "Momos",
    continent: "Indian",
  ),
  FoodItems(
    name: "Chinese Momos",
    price: 7.33,
    rating: 4.3,
    noOfPeople: 180,
    img: "assets/chineasemomos.png",
    description: "Classic Chinese-style dumplings.",
    category: "Momos",
    continent: "Chinese",
  ),
  FoodItems(
    name: "Fried Momos",
    price: 8.67,
    rating: 4.5,
    noOfPeople: 200,
    img: "assets/friedmomos.png",
    description: "Crispy fried momos served with chutney.",
    category: "Momos",
    continent: "Asia",
  ),
  FoodItems(
    name: "Kurkure Momos",
    price: 9.33,
    rating: 4.6,
    noOfPeople: 160,
    img: "assets/kurkuremomos.png",
    description: "Crunchy, kurkure-coated momos.",
    category: "Momos",
    continent: "Asia",
  ),
  FoodItems(
    name: "Soya Momos",
    price: 6.67,
    rating: 4.4,
    noOfPeople: 120,
    img: "assets/soyamomos.png",
    description: "Momos filled with soya chunks and spices.",
    category: "Momos",
    continent: "Asia",
  ),
];
List<FoodItems> pizzaList = [
  FoodItems(
    name: "Chicken Pizza",
    price: 16.67,
    rating: 4.7,
    noOfPeople: 300,
    img: "assets/chickenpizza.png",
    description: "Delicious pizza topped with marinated chicken and cheese.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "Corn Pizza",
    price: 14.67,
    rating: 4.5,
    noOfPeople: 180,
    img: "assets/cornpizza.png",
    description: "Cheesy pizza topped with sweet corn kernels and veggies.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "Mix Veg Pizza",
    price: 13.33,
    rating: 4.3,
    noOfPeople: 250,
    img: "assets/mixvegpizza.png",
    description: "Pizza loaded with a mix of fresh vegetables and cheese.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "Momos Pizza",
    price: 16.00,
    rating: 4.6,
    noOfPeople: 220,
    img: "assets/momospizza.png",
    description: "A unique pizza topped with crispy fried momos.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "Paneer Pizza",
    price: 15.33,
    rating: 4.4,
    noOfPeople: 210,
    img: "assets/paneerpizza.png",
    description: "Pizza topped with soft paneer cubes and herbs.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "Pepperoni Pizza",
    price: 18.00,
    rating: 4.8,
    noOfPeople: 320,
    img: "assets/pepronipizza.png",
    description: "Classic pepperoni pizza with crispy pepperoni slices and cheese.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "BBQ Pizza",
    price: 17.33,
    rating: 4.7,
    noOfPeople: 280,
    img: "assets/bbqpizza.png",
    description: "Savory BBQ sauce with grilled chicken and veggies.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "Hawaiian Pizza",
    price: 15.00,
    rating: 4.5,
    noOfPeople: 230,
    img: "assets/hawaiianpizza.png",
    description: "Tropical Hawaiian pizza topped with ham and pineapple.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "Margherita Pizza",
    price: 12.67,
    rating: 4.2,
    noOfPeople: 200,
    img: "assets/margheritapizza.png",
    description: "Classic Margherita with fresh mozzarella, tomatoes, and basil.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "Sicilian Pizza",
    price: 16.00,
    rating: 4.6,
    noOfPeople: 270,
    img: "assets/sicilianpizza.png",
    description: "Thick crust Sicilian pizza with tomato, onions, and anchovies.",
    category: "Pizza",
    continent: "Global",
  ),
  FoodItems(
    name: "Taco Pizza",
    price: 17.00,
    rating: 4.7,
    noOfPeople: 250,
    img: "assets/tacopizza.png",
    description: "Fusion taco pizza with seasoned beef, cheese, and taco toppings.",
    category: "Pizza",
    continent: "Global",
  ),
];
List<FoodItems> samosaList = [
  FoodItems(
    name: "Aloo Samosa",
    price: 1.33,
    rating: 4.6,
    noOfPeople: 150,
    img: "assets/aloosamosa.png",
    description: "Classic samosa stuffed with spiced mashed potatoes.",
    category: "Samosa",
    continent: "Indian",
  ),
  FoodItems(
    name: "Chowmein Samosa",
    price: 1.67,
    rating: 4.5,
    noOfPeople: 120,
    img: "assets/chowmeinsamosa.png",
    description: "Crispy samosa filled with stir-fried noodles and veggies.",
    category: "Samosa",
    continent: "Indian",
  ),
  FoodItems(
    name: "Macaroni Samosa",
    price: 2.00,
    rating: 4.4,
    noOfPeople: 100,
    img: "assets/macaronisamosa.png",
    description: "Samosa stuffed with creamy and cheesy macaroni.",
    category: "Samosa",
    continent: "Indian",
  ),
  FoodItems(
    name: "Paneer Samosa",
    price: 2.33,
    rating: 4.7,
    noOfPeople: 130,
    img: "assets/paneersamosa.png",
    description: "Samosa filled with spiced paneer and herbs.",
    category: "Samosa",
    continent: "Indian",
  ),
  FoodItems(
    name: "Pasta Samosa",
    price: 2.00,
    rating: 4.5,
    noOfPeople: 110,
    img: "assets/pastasamosa.png",
    description: "Samosa stuffed with pasta in a tangy sauce.",
    category: "Samosa",
    continent: "Indian",
  ),
  FoodItems(
    name: "Pizza Samosa",
    price: 2.67,
    rating: 4.8,
    noOfPeople: 140,
    img: "assets/pizzasamosa.png",
    description: "Crispy samosa filled with pizza toppings and cheese.",
    category: "Samosa",
    continent: "Indian",
  ),
  FoodItems(
    name: "Cheese Samosa",
    price: 2.33,
    rating: 4.6,
    noOfPeople: 150,
    img: "assets/cheesesamosa.png",
    description: "Samosa filled with rich, melted cheese.",
    category: "Samosa",
    continent: "Indian",
  ),
  FoodItems(
    name: "Mushroom Samosa",
    price: 2.67,
    rating: 4.5,
    noOfPeople: 120,
    img: "assets/mushroomsamosa.png",
    description: "Samosa stuffed with spiced mushrooms and herbs.",
    category: "Samosa",
    continent: "Indian",
  ),
];



